// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZYfsghXHy3d6deEG51sUrj5MewQK6Ubs',
    appId: '1:125997358966:web:ddb95194b153cded51a457',
    messagingSenderId: '125997358966',
    projectId: 'xshoppers-3d89e',
    authDomain: 'xshoppers-3d89e.firebaseapp.com',
    storageBucket: 'xshoppers-3d89e.firebasestorage.app',
    measurementId: 'G-KFXS0R1L6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAImg9RQjen2YAaW9bWZS5r3fuWmrTeQMc',
    appId: '1:125997358966:android:ce9cdbead76f446051a457',
    messagingSenderId: '125997358966',
    projectId: 'xshoppers-3d89e',
    storageBucket: 'xshoppers-3d89e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjEa8QSISxBo22skEZQzBMe5UZ8cexek',
    appId: '1:125997358966:ios:32d391e0eece9d1b51a457',
    messagingSenderId: '125997358966',
    projectId: 'xshoppers-3d89e',
    storageBucket: 'xshoppers-3d89e.firebasestorage.app',
    iosBundleId: 'com.example.goShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwjEa8QSISxBo22skEZQzBMe5UZ8cexek',
    appId: '1:125997358966:ios:32d391e0eece9d1b51a457',
    messagingSenderId: '125997358966',
    projectId: 'xshoppers-3d89e',
    storageBucket: 'xshoppers-3d89e.firebasestorage.app',
    iosBundleId: 'com.example.goShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZYfsghXHy3d6deEG51sUrj5MewQK6Ubs',
    appId: '1:125997358966:web:157157555b6ecc5d51a457',
    messagingSenderId: '125997358966',
    projectId: 'xshoppers-3d89e',
    authDomain: 'xshoppers-3d89e.firebaseapp.com',
    storageBucket: 'xshoppers-3d89e.firebasestorage.app',
    measurementId: 'G-LHMJES1Q21',
  );
}
